## 1
outcome <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
head(outcome)
ncol(outcome)
outcome[, 11] <- as.numeric(outcome[, 11])
hist(outcome[, 11])
title("Heart Attack 30-day Death Rate")
hist(outcome[, 11], xlab = "30-day Death Rate", main = "Heart Attack 30-day Death Rate")
## 2
par(mfrow = c(3, 1))
outcome[, 17] <- as.numeric(outcome[, 17])
outcome[, 23] <- as.numeric(outcome[, 23])
hist(outcome[, 11])
hist(outcome[, 17])
hist(outcome[, 23])
par(mfrow = c(3, 1))
hist(outcome[, 11], xlab = "30-day Death Rate", main = "Heart Attack 30-day Death Rate")
hist(outcome[, 17], xlab = "30-day Death Rate", main = "Heart Failure 30-day Death Rate")
hist(outcome[, 23], xlab = "30-day Death Rate", main = "Pneumonia 30-day Death Rate")
lims <- c(range(outcome[,23], na.rm = T),range(outcome[,17], na.rm = T),range(outcome[,11], na.rm = T))
xl <- c(min(lims),max(lims))
m1 = median(outcome[,11], na.rm = T)
hist(outcome[, 11], xlim = xl, xlab = substitute("30-day Death Rate, " * bar(x) == m11, list(m11 = m1)), main = "Heart Attack 30-day Death Rate")
abline(v = m1, lwd = 2, col = "blue")
m2 = median(outcome[,17], na.rm = T)
hist(outcome[, 17], xlim = xl, xlab = substitute("30-day Death Rate, " * bar(x) == m22, list(m22 = m2)), main = "Heart Failure 30-day Death Rate")
abline(v = m2, lwd = 2, col = "green")
m3 = median(outcome[,23], na.rm = T)
hist(outcome[, 23], xlim = xl, xlab = substitute("30-day Death Rate, " * bar(x) == m33, list(m33 = m3)), main = "Pneumonia 30-day Death Rate")
abline(v = m3, lwd = 2, col = "red")